# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Modeling Electrochemical Systems
author: Steven C. DeCaluwe
logo: images/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: EchemSysEng.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - EchemSysEng_bib.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/decaluwe/EchemSystemsEngingeering.git  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Use thebe to launch interactive code blocks
launch_buttons:
  thebe                  : true
  binderhub_url: https://mybinder.org/v2/gh/decaluwe/EchemSystemsEngingeering.git/main  # The URL for your BinderHub (e.g., https://mybinder.org)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
